# Week 4 · Day 1 — Assignment: My First NumPy Analysis
### Code to AI — Python & Data Science

---
**Instructions:**
- Complete every task below. Write your code under each `# YOUR CODE HERE`.
- Keep it simple and clean. Add a short comment explaining each step.
- When done: save the notebook, push it to your GitHub repo, and post the link in the WhatsApp group. ✅
- Due **before the next class**.

Start by importing NumPy.

In [2]:
import numpy as np

## Task 1 — Create your data
You recorded the number of glasses of water you drank each day for one week:
`2, 5, 3, 6, 4, 7, 5`

1. Store these in a NumPy array called `water`.
2. Print the array, its `shape`, and its `size`.

In [ ]:
# YOUR CODE HERE
import numpy as np

water = np.array([2,5,3,6,4,7,5]) # creating array

print(water.shape) # shape of array
print(water.size) # size of array


(7,)
7


## Task 2 — Slicing practice
From the `water` array:
1. Print the first 3 days.
2. Print the last 2 days.
3. Print only the weekend (day 6 and day 7 — positions 5 and 6).

In [ ]:
# YOUR CODE HERE
print(water[:3]) # first e days
print(water[-2:]) # last 2 days
print(water[5:]) # weekends

[2 5 3]
[7 5]
[7 5]


## Task 3 — Vectorized math
Each glass is 250 ml.
1. In one line, create a new array `water_ml` = glasses × 250.
2. Print the milliliters for each day.

In [ ]:
# YOUR CODE HERE
water_ml = water * 250 # liter ti milliliter

print(water_ml)

[ 500 1250  750 1500 1000 1750 1250]


## Task 4 — Build a 2D array
Create a 2D array called `scores` with 2 rows and 3 columns representing two students' marks in three subjects:

Student A: 80, 75, 90
Student B: 60, 85, 70

Then print:
1. The shape of the array.
2. Student B's Maths mark (row 1, column 0).
3. The whole first column (everyone's first subject).

In [ ]:
# YOUR CODE HERE
scores = np.array([[80,75,90],
                    [60,85,70]]) # creating a multidemensional array of 2 rows and 3 columns

print(scores.shape) # shape of array
print(scores[1,0])  # score at second row and first coloumn
print(scores[:,0])  # scores in first column

(2, 3)
60
[80 60]


## Task 5 — Mini challenge
Use `np.arange` to create an array of numbers from 1 to 10.
Then, in one line, create a new array that contains the **square** of each number (multiply the array by itself). Print both.

In [ ]:
# YOUR CODE HERE
arr = np.arange(1,10) # creating an array

square_arr = arr * arr # square of array

print(arr)
print(square_arr)

[1 2 3 4 5 6 7 8 9]
[ 1  4  9 16 25 36 49 64 81]


### ✅ Before you submit
- [ ] Every cell runs without errors (Run All)
- [ ] Each task has a short comment
- [ ] Notebook saved and pushed to GitHub
- [ ] Repo link posted in the WhatsApp group

Great job finishing Day 1! 🎉